CREATE TABLE `ps_out_order` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `status` tinyint(1) NOT NULL DEFAULT '1' COMMENT '状态 1待确认 2已确认 3已放行 4已作废',
  `community_id` varchar(30) NOT NULL DEFAULT '0' COMMENT '小区id',
  `groupId` varchar(30) NOT NULL DEFAULT '' COMMENT '苑期区',
  `buildingId` varchar(30) NOT NULL DEFAULT '' COMMENT '幢',
  `unitId` varchar(30) NOT NULL DEFAULT '' COMMENT '单元',
  `roomId` varchar(30) NOT NULL DEFAULT '' COMMENT '房屋id',
  `application_name` varchar(10) NOT NULL DEFAULT '' COMMENT '申请人',
  `application_mobile` varchar(12) NOT NULL DEFAULT '' COMMENT '申请人电话',
  `member_type` tinyint(2) NOT NULL DEFAULT '0' COMMENT '申请人身份 1=业主 2=家人 3=租客',
  `room_address` varchar(255) NOT NULL DEFAULT '' COMMENT '房屋地址',
  `application_id` varchar(30) NOT NULL DEFAULT '0' COMMENT '申请人id(member_id`)',
  `application_at` int(11) NOT NULL DEFAULT '0' COMMENT '申请日期',
  `code` varchar(10) NOT NULL DEFAULT '' COMMENT '出门唯一标识',
  `qr_url` varchar(255) NOT NULL DEFAULT '' COMMENT '出门二维码',
  `content` text COMMENT '出门单内容',
  `content_img` text COMMENT '出门单内容图片',
  `car_number` varchar(10) NOT NULL DEFAULT '' COMMENT '车牌号',
  `release_at` int(11) NOT NULL DEFAULT '0' COMMENT '出门时间',
  `release_id` varchar(30) NOT NULL DEFAULT '0' COMMENT '放行人id',
  `release_name` varchar(10) NOT NULL DEFAULT '' COMMENT '放行人名称',
  `check_id` varchar(30) NOT NULL DEFAULT '0' COMMENT '审核人id',
  `check_name` varchar(10) NOT NULL DEFAULT '' COMMENT '审核人名称',
  `check_at` int(11) NOT NULL DEFAULT '0' COMMENT '审核时间',
  `ali_form_id` varchar(100) NOT NULL DEFAULT '' COMMENT '小程序表单id，用户消息推送',
  `ali_user_id` varchar(100) NOT NULL DEFAULT '' COMMENT '小程序用户id，用户消息推送',
  `create_at` int(11) NOT NULL DEFAULT '0' COMMENT '提交订单时间',
  `update_at` int(11) NOT NULL DEFAULT '0' COMMENT '提交订单时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='出门单';
