CREATE TABLE `ps_room_visitor` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `room_id` int(11) NOT NULL DEFAULT '0' COMMENT '房屋id',
  `community_id` int(11) NOT NULL DEFAULT '0' COMMENT '小区id',
  `community_name` varchar(100) DEFAULT NULL COMMENT '小区名称',
  `group` varchar(32) NOT NULL DEFAULT '' COMMENT '苑期区',
  `building` varchar(32) NOT NULL DEFAULT '' COMMENT '幢',
  `unit` varchar(32) NOT NULL DEFAULT '' COMMENT '单元',
  `room` varchar(64) NOT NULL DEFAULT '' COMMENT '室',
  `app_user_id` int(11) NOT NULL DEFAULT '0' COMMENT '添加此访客的支付宝用户id',
  `member_id` int(11) NOT NULL DEFAULT '0' COMMENT '住户id',
  `name` varchar(50) NOT NULL DEFAULT '' COMMENT '访客姓名',
  `mobile` varchar(15) NOT NULL DEFAULT '' COMMENT '访客手机号',
  `car_number` varchar(15) NULL DEFAULT '' COMMENT '车牌号',
  `password` varchar(20) NOT NULL DEFAULT '' COMMENT '访客密码',
  `qrcode` varchar(255) NOT NULL DEFAULT '' COMMENT '二维码url',
   `sex` tinyint(1) NULL DEFAULT '1' COMMENT '性别，1男，2女',
  `is_car` tinyint(1) NULL DEFAULT '2' COMMENT '是否驾车 1是 2否',
  `status` tinyint(1) NULL DEFAULT '1' COMMENT '访问状态 1待访 2已访',
  `is_msg` tinyint(1) NULL DEFAULT '2' COMMENT '发送短信 1已发 2未发',
  `visit_at` int(11) NOT NULL DEFAULT '0' COMMENT '到访时间',
  `pass_at` int(10) NULL DEFAULT '0' COMMENT '通行时间',
  `create_at` int(11) NOT NULL DEFAULT '0' COMMENT '添加时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='房屋对应的访客表';